[workspace]
resolver = "2"
members = ["bindgen", "winui3"]
default-members = ["winui3"]

[workspace.dependencies]
windows-bindgen = "0.100"
windows-collections = "0.100"
windows-core = "0.100"
windows-future = "0.100"
windows-numerics = "0.100"
windows-reference = "0.100"
windows-time = "0.100"
winui3 = { path = "winui3", package = "winio-winui3" }
