[package]
name = "winio-winui3"
version = "0.5.0"
edition = "2024"
description = "WinUI3 bindings (subset) for Rust"
categories = ["os::windows-apis", "gui"]
keywords = ["winui", "gui"]
authors = ["Alovchin91", "Berrysoft <Strawberry_Str@hotmail.com>"]
license = "MIT"
repository = "https://github.com/compio-rs/winui3-rs"

[lib]
name = "winui3"

[dependencies]
windows-collections.workspace = true
windows-core.workspace = true
windows-future.workspace = true
windows-numerics.workspace = true
windows-reference.workspace = true
windows-time.workspace = true
