#[cfg(feature = "Win32_System_Com")]
pub mod Com;
#[cfg(feature = "Win32_System_LibraryLoader")]
pub mod LibraryLoader;
#[cfg(feature = "Win32_System_Memory")]
pub mod Memory;
#[cfg(feature = "Win32_System_Ole")]
pub mod Ole;
#[cfg(feature = "Win32_System_Registry")]
pub mod Registry;
#[cfg(feature = "Win32_System_Variant")]
pub mod Variant;
#[cfg(feature = "Win32_System_WinRT")]
pub mod WinRT;
